In [1]:
import numpy as np
import pandas as pd



dict=[[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9],[5,6,7,8,9,10]]
data=pd.DataFrame(dict)
print(data)
for indexs in data.index:
    print(data.loc[indexs].values[:])

   0  1  2  3  4   5
0  1  2  3  4  5   6
1  2  3  4  5  6   7
2  3  4  5  6  7   8
3  4  5  6  7  8   9
4  5  6  7  8  9  10
[1 2 3 4 5 6]
[2 3 4 5 6 7]
[3 4 5 6 7 8]
[4 5 6 7 8 9]
[ 5  6  7  8  9 10]


In [0]:
df = pd.DataFrame(np.arange(12).reshape(3,4), columns=['A', 'B', 'C', 'D'])

In [3]:
df

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [4]:
df.drop(['B', 'C'], axis=1)


A   D
0  0   3
1  4   7
2  8  11

In [5]:
df.drop(columns=['B', 'C'])

A   D
0  0   3
1  4   7
2  8  11

In [6]:
df.drop([0, 1])

A  B   C   D
2  8  9  10  11

In [7]:
df['D'].tolist()

[3, 7, 11]

In [8]:
# inplace = True
# inplace=False，默认该删除操作不改变原数据，而是返回一个执行删除操作后的新dataframe；

# inplace=True，则会直接在原数据上进行删除操作，删除后就回不来了。

TypeError: ignored