In [1]:
from numpy import *

def loadDataSet():
    list = [[1, 3, 4], [2, 3, 5], [1, 2, 3, 5], [2, 5]]
    return list

In [2]:
def createC1(dataSet):
    C1 = [] #C1是大小为1的所有候选项集的集合
    for transaction in dataSet:
        for item in transaction:
            if not ([item] in C1):
                C1.append([item])             
    C1.sort()
    return map(frozenset, C1)#use frozen set so we can use it as a key in a dict  

In [3]:
#D表示数据集，CK表示候选项集，minSupport表示最小的支持度，自己设定
def scanD(D, Ck, minSupport):
    ssCnt = {}
    for tid in D:
        for can in Ck:
            if can.issubset(tid):
                if not ssCnt.has_key(can): 
                    ssCnt[can]=1
                else: 
                    ssCnt[can] += 1
    numItems = float(len(D))
    retList = [] #存储满足最小支持度要求的项集
    supportData = {} #每个项集的支持度字典
    for key in ssCnt:  #计算所有项集的支持度
        support = ssCnt[key]/numItems
        if support >= minSupport:
            retList.insert(0,key)
        supportData[key] = support
    return retList, supportData

In [4]:
#LK是频繁项集列表，K表示接下来合并的项集中的单个想的个数{1,2,3}表示k=3
def aprioriGen(Lk, k): #creates Ck
    retList = []
    lenLk = len(Lk)
    for i in range(lenLk):
        for j in range(i+1, lenLk): 
            L1 = list(Lk[i])[:k-2]; L2 = list(Lk[j])[:k-2] #前k-2个项相同时，将两个集合合并
            L1.sort(); L2.sort()
            if L1==L2: #if first k-2 elements are equal
                retList.append(Lk[i] | Lk[j]) #set union
    return retList 

In [5]:
#只需要输入数据集和支持度即可
def apriori(dataSet, minSupport = 0.5):
    C1 = createC1(dataSet)
    D = map(set, dataSet)
    L1, supportData = scanD(D, C1, minSupport)
    L = [L1]
    k = 2
    while (len(L[k-2]) > 0):
        Ck = aprioriGen(L[k-2], k)
        Lk, supK = scanD(D, Ck, minSupport)#scan DB to get Lk
        supportData.update(supK)
        L.append(Lk)
        k += 1
    return L, supportData#返回频繁项集和每个项集的支持度值

In [6]:
#输入的参数分别为：频繁项集、支持度数据字典、自定义的最小支持度，返回的是可信度规则列表
def generateRules(L, supportData, minConf=0.7):  #支持度是通过scanD得到的字典
    bigRuleList = []
    for i in range(1, len(L)):#只去频繁项集中元素个数大于2的子集，如{1,2}{1,2,3}，不取{2}{3},etc...
        for freqSet in L[i]:
            H1 = [frozenset([item]) for item in freqSet]
            if (i > 1):
                rulesFromConseq(freqSet, H1, supportData, bigRuleList, minConf)
            else:
                calcConf(freqSet, H1, supportData, bigRuleList, minConf)
    return bigRuleList         

In [7]:
#计算可信度，找到满足最小可信度的要求规则
def calcConf(freqSet, H, supportData, brl, minConf=0.7):
    prunedH = [] #create new list to return
    for conseq in H:
        conf = supportData[freqSet]/supportData[freqSet-conseq] #calc confidence
        if conf >= minConf: 
            print freqSet-conseq,'-->',conseq,'conf:',conf
            brl.append((freqSet-conseq, conseq, conf))
            prunedH.append(conseq)
    return prunedH

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print freqSet-conseq,'-->',conseq,'conf:',conf)? (<ipython-input-7-ed57904fb262>, line 7)

In [9]:
x = {1:'a',2:'b'}
x = {v:k for k,v in x.items()}
for idx,item in enumerate(x):
    print(idx)
    print(item)

0
a
1
b


In [10]:
x


{'a': 1, 'b': 2}

In [11]:
s = sorted(x.keys())
s

['a', 'b']

In [12]:
(1,2) + (2,)

(1, 2, 2)

In [13]:
import numpy as np

In [19]:
x = np.zeros((3,3),dtype = bool)
x

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [20]:
x[0][0] 

False

In [29]:
x[0][0] = True
x[1][1] = True
x[1][2] = True

In [30]:
x

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False]])

In [31]:
cur_freq_itemset_id = [1,2] # 相当于把对应列抽出来
x[:,cur_freq_itemset_id]

array([[False, False],
       [ True,  True],
       [False, False]])

In [32]:
np.prod(x[:,cur_freq_itemset_id],1)

array([0, 1, 0])

In [33]:
1.0 * np.prod(x[:,cur_freq_itemset_id],1)

array([0., 1., 0.])

In [34]:
1.0 * sum(np.prod(x[:,cur_freq_itemset_id],1))

1.0

In [35]:
[1,2] + (3,)

TypeError: can only concatenate list (not "tuple") to list

In [36]:
(1,2) + (3,)

(1, 2, 3)